# Generated by Django 4.0 on 2021-12-20 20:55

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255)),
                ('exposure_from', models.DateTimeField()),
                ('exposure_to', models.DateTimeField()),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=10)),
                ('zone', models.CharField(max_length=255)),
                ('last_updated', models.DateTimeField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
