# Generated by Django 4.0 on 2021-12-20 21:19

from django.db import migrations
from django.contrib.gis.geos import fromstr
from pathlib import Path
from datetime import datetime

DATA_FILENAME = 'data.txt'


def load_data(apps, schema_editor):
    covid_exposure = apps.get_model('map_ns_covid_exposures', 'CovidExposure')

    file = open(DATA_FILENAME, "r")
    for line in file:

        fields = line.split("\",\"")

        place = fields[0].strip("\"")

        #exposure_from = "TO_DATE(\'%s\', \'YYYY-MM-DD HH:MM\')" % fields[1].strip("\"")
        #exposure_to = "TO_DATE(\'%s\', \'YYYY-MM-DD HH:MM\')" % fields[2].strip("\"")
        exposure_from = fields[1].strip("\"")
        exposure_to = fields[2].strip("\"")


        address = fields[3].strip("\"")
        exposure_type = fields[4].strip("\"")
        zone = fields[5].strip("\"")
        #last_updated = "TO_DATE(\'%s\', \'YYYY-MM-DD HH:MM\')" % fields[6].strip("\"")
        last_updated = fields[6].strip("\"")


        location = fromstr("POINT(%s %s)" % (fields[8].strip("\"\n"), fields[7].strip("\"")), srid=4326)

        covid_exposure(place=place, exposure_from=exposure_from, exposure_to=exposure_to, address=address,
                       type=exposure_type, zone=zone, last_updated=last_updated, location=location).save()

    file.close()


class Migration(migrations.Migration):

    dependencies = [
        ('map_ns_covid_exposures', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_data)
    ]
